version: '3.8'
services:
  api1: 
    build: .
    ports:
      - "3000:3000"
  api2: 
    build: .
    ports:
      - "3001:3000"
  nginx:
    image: nginx
    hostname: api
    volumes:
      - ./:/etc/nginx/
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"


